/**
 * NASEC Chart of Accounts 2026.
 * Source: Chart of Accounts 2026 (1).doc
 */
export type CoaSeed = {
  code: string;
  name: string;
  type: "asset" | "liability" | "equity" | "income" | "expense";
  subType: string;
  parentCode?: string;
  currency?: string;
  isBank?: boolean;
  isCash?: boolean;
  isControl?: boolean;
  vatApplicable?: boolean;
};

export const NASEC_COA_2026: CoaSeed[] = [
  { code: "1000000", name: "ASSETS", type: "asset", subType: "current-asset" },
  {
    code: "1100000",
    name: "CURRENT ASSETS",
    type: "asset",
    subType: "current-asset",
    parentCode: "1000000",
  },
  {
    code: "1101000",
    name: "CASH IN HAND",
    type: "asset",
    subType: "current-asset",
    parentCode: "1100000",
    isCash: true,
    currency: "AED",
  },
  {
    code: "1101001",
    name: "PETTY CASH ADVANCE",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101000",
    isCash: true,
    currency: "AED",
  },
  {
    code: "1101002",
    name: "CCW CASH FOR REFUND",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101000",
    isCash: true,
    currency: "AED",
  },
  {
    code: "1101003",
    name: "CASH COLLECTION",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101000",
    isCash: true,
    currency: "AED",
  },
  {
    code: "1101004",
    name: "HISTORICAL RECONSTRUCTION - CASH",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101000",
    isCash: true,
    currency: "AED",
  },
  {
    code: "1101100",
    name: "INVOICES GENERATED YEAR-2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101000",
  },
  {
    code: "1101101",
    name: "INVOICES - JAN.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101102",
    name: "INVOICES - FEB.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101103",
    name: "INVOICES - MAR.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101104",
    name: "INVOICES - APR.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101105",
    name: "INVOICES - MAY.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101106",
    name: "INVOICES - JUN.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101107",
    name: "INVOICES - JUL.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101108",
    name: "INVOICES - AUG.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101109",
    name: "INVOICES - SEP.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101110",
    name: "INVOICES - OCT.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101111",
    name: "INVOICES - NOV.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1101112",
    name: "INVOICES - DEC.2026",
    type: "asset",
    subType: "current-asset",
    parentCode: "1101100",
  },
  {
    code: "1102000",
    name: "BANKS",
    type: "asset",
    subType: "current-asset",
    parentCode: "1100000",
    isBank: true,
    currency: "AED",
  },
  {
    code: "1102100",
    name: "COMMERCIAL BANK OF DUBAI",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102000",
    isBank: true,
    currency: "AED",
  },
  {
    code: "1102101",
    name: "CBD 1001577558",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102100",
    isBank: true,
    currency: "AED",
  },
  {
    code: "1102200",
    name: "BANK GUARANTEE",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102000",
  },
  {
    code: "1102201",
    name: "JVC PROJ BANK GUARANTEE",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102200",
  },
  {
    code: "1102202",
    name: "WASL LABOUR CAMP R1104 BANK GUARANTEE",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102200",
  },
  {
    code: "1102203",
    name: "WASL SOUQ DISTRICT R1004 BANK GUARANTEE",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102200",
  },
  {
    code: "1102300",
    name: "ABU DHABI COMMERCIAL BANK",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102000",
    isBank: true,
    currency: "AED",
  },
  {
    code: "1102301",
    name: "ADCB 14246809910001",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102300",
    isBank: true,
    currency: "AED",
  },
  {
    code: "1102302",
    name: "ADCB 14246809920001",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102300",
    isBank: true,
    currency: "AED",
  },
  {
    code: "1102400",
    name: "HISTORICAL RECONSTRUCTION - BANKS",
    type: "asset",
    subType: "current-asset",
    parentCode: "1102000",
    isBank: true,
    currency: "AED",
  },
  {
    code: "1103000",
    name: "ACCOUNTS RECEIVABLES",
    type: "asset",
    subType: "current-asset",
    parentCode: "1100000",
    isControl: true,
  },
  {
    code: "1103001",
    name: "CHEQUE RETURNS",
    type: "asset",
    subType: "current-asset",
    parentCode: "1103000",
  },
  {
    code: "1103002",
    name: "RETENTION RECEIVABLE",
    type: "asset",
    subType: "current-asset",
    parentCode: "1103000",
  },
  {
    code: "1103003",
    name: "A/R CLIENTS 2023",
    type: "asset",
    subType: "current-asset",
    parentCode: "1103000",
  },
  {
    code: "1103004",
    name: "A/R CLIENTS 2024",
    type: "asset",
    subType: "current-asset",
    parentCode: "1103000",
  },
  {
    code: "1103005",
    name: "OTHER RECEIVABLES",
    type: "asset",
    subType: "current-asset",
    parentCode: "1103000",
  },
  {
    code: "1103006",
    name: "A/R CLIENTS 2025",
    type: "asset",
    subType: "current-asset",
    parentCode: "1103000",
  },
  {
    code: "1103007",
    name: "HISTORICAL RECONSTRUCTION - A/R",
    type: "asset",
    subType: "current-asset",
    parentCode: "1103000",
  },
  {
    code: "1104000",
    name: "STAFF LOANS",
    type: "asset",
    subType: "current-asset",
    parentCode: "1100000",
  },
  {
    code: "1104001",
    name: "MOHD IBRAHIM",
    type: "asset",
    subType: "current-asset",
    parentCode: "1104000",
  },
  {
    code: "1105000",
    name: "SECURITY DEPOSITS",
    type: "asset",
    subType: "current-asset",
    parentCode: "1100000",
  },
  {
    code: "1105001",
    name: "VISA DEPOSIT",
    type: "asset",
    subType: "current-asset",
    parentCode: "1105000",
  },
  {
    code: "1105002",
    name: "DEWA DEPOSIT",
    type: "asset",
    subType: "current-asset",
    parentCode: "1105000",
  },
  {
    code: "1105003",
    name: "DXB MUNICIPALITY DEPOSIT",
    type: "asset",
    subType: "current-asset",
    parentCode: "1105000",
  },
  {
    code: "1105004",
    name: "PERFORMANCE SECURITY",
    type: "asset",
    subType: "current-asset",
    parentCode: "1105000",
  },
  {
    code: "1105005",
    name: "HISTORICAL RECONSTRUCTION - DEPOSITS RECOVERABL",
    type: "asset",
    subType: "current-asset",
    parentCode: "1105000",
  },
  {
    code: "1106000",
    name: "HISTORICAL RECONSTRUCTION - OTHER RECEIVABLES",
    type: "asset",
    subType: "current-asset",
    parentCode: "1100000",
  },
  {
    code: "1200000",
    name: "FIXED ASSETS",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1000000",
  },
  {
    code: "1201000",
    name: "FURNITURE & FIXTURES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1200000",
  },
  {
    code: "1201001",
    name: "OFFICE FURNITURE",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1201000",
  },
  {
    code: "1201002",
    name: "OFFICE DECORATION",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1201000",
  },
  {
    code: "1202000",
    name: "VEHICLES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1200000",
  },
  {
    code: "1202001",
    name: "COMPANY OWNED VEHICLES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1202000",
  },
  {
    code: "1203000",
    name: "MACHINERIES & EQUIPMENTS",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1200000",
  },
  {
    code: "1203001",
    name: "OFFICE EQUIPMENT",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1203000",
  },
  {
    code: "1203002",
    name: "EQUIPMENTS FOR DAILY OPERATIONS",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1203000",
  },
  {
    code: "1204000",
    name: "SOFTWARES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1200000",
  },
  {
    code: "1204001",
    name: "ENGINEERING SOFTWARES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1204000",
  },
  {
    code: "1205000",
    name: "YEARLY PREPAID EXPENSES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1200000",
  },
  {
    code: "1205001",
    name: "PREPAID EXPENSES Y-2026",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1205000",
  },
  {
    code: "1205002",
    name: "HISTORICAL RECONSTRUCTION - PREPAYMENTS",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1205000",
  },
  {
    code: "1206000",
    name: "PARTNERS DRAWING ACCOUNT",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1200000",
  },
  {
    code: "1206001",
    name: "MOHD. HILAL BIN TARAF DRAWING A/C",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1206000",
  },
  {
    code: "1207000",
    name: "LOAN TO AFFILIATES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1200000",
  },
  {
    code: "1207001",
    name: "NAS R/E BRANCH ACCOUNT",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1207000",
  },
  {
    code: "1300000",
    name: "ACCUMULATED DEPRECIATION",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1000000",
  },
  {
    code: "1301000",
    name: "ACCUM. DEP. FURNITURE & FIXTURES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1300000",
  },
  {
    code: "1301001",
    name: "ACCUM. DEP, OFFC FURNITURE",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1301000",
  },
  {
    code: "1301002",
    name: "ACCUM. DEP, OFFC DECORATION",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1301000",
  },
  {
    code: "1302000",
    name: "ACCUM. DEP. VEHICLES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1300000",
  },
  {
    code: "1302001",
    name: "ACCUM. DEP. CO. OWN VEHICLES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1302000",
  },
  {
    code: "1303000",
    name: "ACCUM. DEP. MACHINERIES & EQUIPMENTS",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1300000",
  },
  {
    code: "1303001",
    name: "ACCUM. DEP. OFFICE EQUIPMENT",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1303000",
  },
  {
    code: "1303002",
    name: "ACCUM. DEP. EQUIP FOR DAILY OPERATIONS",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1303000",
  },
  {
    code: "1304000",
    name: "ACCUM. DEP. SOFTWARES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1300000",
  },
  {
    code: "1304001",
    name: "ACCUM. DEP. ENGR SOFTWARES",
    type: "asset",
    subType: "fixed-asset",
    parentCode: "1304000",
  },
  {
    code: "2000000",
    name: "LIABILITIES",
    type: "liability",
    subType: "current-liability",
  },
  {
    code: "2100000",
    name: "CURRENT LIABILITIES",
    type: "liability",
    subType: "current-liability",
    parentCode: "2000000",
  },
  {
    code: "2101000",
    name: "P.D.C. PAYABLE",
    type: "liability",
    subType: "current-liability",
    parentCode: "2100000",
  },
  {
    code: "2101001",
    name: "P.D.C. PAYABLE 2026",
    type: "liability",
    subType: "current-liability",
    parentCode: "2101000",
  },
  {
    code: "2102000",
    name: "SUPPLIERS / CONTRACTORS ACCOUNT",
    type: "liability",
    subType: "current-liability",
    parentCode: "2100000",
    isControl: true,
  },
  {
    code: "2102001",
    name: "ICT INFORMATION SYSTEMS",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102002",
    name: "ORIENT INSURANCE PJSC",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102003",
    name: "SCHEDULE CONTRACTING",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102004",
    name: "DEZIRE PROJECT CONSULTANT",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102005",
    name: "UNION INSURANCE",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102006",
    name: "AL WARQA SURVEYING",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102007",
    name: "TRAKHEES (HASSAN-JVC)",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102008",
    name: "ALHAIKAL ALSALB CONTRACTING",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102009",
    name: "SUKOON INSURANCE",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102010",
    name: "GLOBALTECH CONSULTANCY",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102011",
    name: "TRANSFAST ENGINEERING LABORATORY",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102012",
    name: "STRUCTURFLEX MIDDLE EAST CONTRACTING",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102013",
    name: "ALFA MATRIX",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102014",
    name: "SAMAR KAREEM - SUBCONTRACTORS",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102015",
    name: "PAYABLE TO NAS REAL ESTATE",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102016",
    name: "JHS FINANCIAL & TAX CONSULTANT CO",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102017",
    name: "AL WATHBA NATIONAL INSURANCE CO",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102018",
    name: "LAND ART STUDIO",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102019",
    name: "ELEVATE BUSINESS SOLUTIONS DMCC",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
    vatApplicable: true,
  },
  {
    code: "2102020",
    name: "SPOGPRINT PORTAL LLC",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102021",
    name: "LIFANG VISION",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102022",
    name: "PROMARK CONSULTANTS",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102023",
    name: "DEMONFOX",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102024",
    name: "PAYABLE TO NAS TRAVELS",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102025",
    name: "HISTORICAL RECONSTRUCTION - A/P",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102026",
    name: "RASHED LOOTAH CONSULTANCIES",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2102027",
    name: "DAMAN INSURANCE",
    type: "liability",
    subType: "current-liability",
    parentCode: "2102000",
  },
  {
    code: "2103000",
    name: "ADVANCE REVENUE",
    type: "liability",
    subType: "current-liability",
    parentCode: "2100000",
  },
  {
    code: "2103001",
    name: "ADVANCE REVENUE RCV Y-2026",
    type: "liability",
    subType: "current-liability",
    parentCode: "2103000",
  },
  {
    code: "2104000",
    name: "YEARLY PROVISIONS",
    type: "liability",
    subType: "current-liability",
    parentCode: "2100000",
  },
  {
    code: "2104001",
    name: "PROVISION EMP. GRATUITY",
    type: "liability",
    subType: "current-liability",
    parentCode: "2104000",
  },
  {
    code: "2104002",
    name: "PROVISION EMP. LEAVE SALARY",
    type: "liability",
    subType: "current-liability",
    parentCode: "2104000",
  },
  {
    code: "2104003",
    name: "PROVISION EMP. AIR TICKETS",
    type: "liability",
    subType: "current-liability",
    parentCode: "2104000",
  },
  {
    code: "2104004",
    name: "PROVISION DOUBTFUL ACCOUNTS",
    type: "liability",
    subType: "current-liability",
    parentCode: "2104000",
  },
  {
    code: "2104005",
    name: "PROVISION FOR CORPORATE TAX",
    type: "liability",
    subType: "current-liability",
    parentCode: "2104000",
  },
  {
    code: "2104006",
    name: "HISTORICAL RECONSTRUCTION - ACCRUALS & PROVISION",
    type: "liability",
    subType: "current-liability",
    parentCode: "2104000",
  },
  {
    code: "2105000",
    name: "OUTSTANDING LIABLITIES",
    type: "liability",
    subType: "current-liability",
    parentCode: "2100000",
  },
  {
    code: "2105001",
    name: "SUSPENSE ACCOUNT",
    type: "liability",
    subType: "current-liability",
    parentCode: "2105000",
  },
  {
    code: "2105002",
    name: "COMMISSION PAYABLE",
    type: "liability",
    subType: "current-liability",
    parentCode: "2105000",
  },
  {
    code: "2105003",
    name: "SALARIES PAYABLE",
    type: "liability",
    subType: "current-liability",
    parentCode: "2105000",
  },
  {
    code: "2200000",
    name: "NON-CURRENT LIABILITIES",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2000000",
  },
  {
    code: "2201000",
    name: "TAXATION",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2200000",
  },
  {
    code: "2201100",
    name: "5% OUTPUT VALUE ADDED TAX",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201000",
    vatApplicable: true,
  },
  {
    code: "2201101",
    name: "OUTPUT VAT - JAN.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201102",
    name: "OUTPUT VAT - FEB.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201103",
    name: "OUTPUT VAT - MAR.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201104",
    name: "OUTPUT VAT - APR.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201105",
    name: "OUTPUT VAT - MAY.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201106",
    name: "OUTPUT VAT - JUN.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201107",
    name: "OUTPUT VAT - JUL.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201108",
    name: "OUTPUT VAT - AUG.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201109",
    name: "OUTPUT VAT - SEP.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201110",
    name: "OUTPUT VAT - OCT.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201111",
    name: "OUTPUT VAT - NOV.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201112",
    name: "OUTPUT VAT - DEC.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201115",
    name: "OUTPUT VAT - NASEC",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201100",
    vatApplicable: true,
  },
  {
    code: "2201200",
    name: "5% INPUT VALUE ADDED TAX",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201000",
    vatApplicable: true,
  },
  {
    code: "2201201",
    name: "INPUT VAT - JAN.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201202",
    name: "INPUT VAT - FEB.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201203",
    name: "INPUT VAT - MAR.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201204",
    name: "INPUT VAT - APR.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201205",
    name: "INPUT VAT - MAY.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201206",
    name: "INPUT VAT - JUN.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201207",
    name: "INPUT VAT - JUL.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201208",
    name: "INPUT VAT - AUG.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201209",
    name: "INPUT VAT - SEP.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201210",
    name: "INPUT VAT - OCT.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201211",
    name: "INPUT VAT - NOV.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201212",
    name: "INPUT VAT - DEC.2026",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  {
    code: "2201215",
    name: "INPUT VAT - NASEC",
    type: "liability",
    subType: "non-current-liability",
    parentCode: "2201200",
    vatApplicable: true,
  },
  { code: "3000000", name: "OWNERS EQUITY", type: "equity", subType: "equity" },
  {
    code: "3100000",
    name: "CAPITAL ACCOUNT",
    type: "equity",
    subType: "equity",
    parentCode: "3000000",
  },
  {
    code: "3101000",
    name: "CAPITAL PROVIDED BY MOHD HELAL",
    type: "equity",
    subType: "equity",
    parentCode: "3100000",
  },
  {
    code: "3200000",
    name: "RETAINED EARNINGS",
    type: "equity",
    subType: "retained-earnings",
    parentCode: "3000000",
  },
  {
    code: "3201000",
    name: "PROFIT & LOSS A/C",
    type: "equity",
    subType: "retained-earnings",
    parentCode: "3200000",
  },
  {
    code: "3202000",
    name: "PRIOR YEAR ADJUSTMENT ACCOUNT",
    type: "equity",
    subType: "retained-earnings",
    parentCode: "3200000",
  },
  {
    code: "3203000",
    name: "PARTNERS CURRENT ACCOUNT - HILAL",
    type: "equity",
    subType: "retained-earnings",
    parentCode: "3200000",
  },
  {
    code: "3204000",
    name: "PARTNERS CURRENT ACCOUNT - ELMEZYEN",
    type: "equity",
    subType: "retained-earnings",
    parentCode: "3200000",
  },
  { code: "4000000", name: "REVENUES", type: "income", subType: "revenue" },
  {
    code: "4100000",
    name: "GENERAL OPERATING REVENUES",
    type: "income",
    subType: "revenue",
    parentCode: "4000000",
  },
  {
    code: "4101000",
    name: "BASIC OPERATING REVENUES",
    type: "income",
    subType: "revenue",
    parentCode: "4100000",
    vatApplicable: true,
  },
  {
    code: "4101001",
    name: "DESIGN REVENUE",
    type: "income",
    subType: "revenue",
    parentCode: "4101000",
    vatApplicable: true,
  },
  {
    code: "4101002",
    name: "SUPERVISION REVENUE",
    type: "income",
    subType: "revenue",
    parentCode: "4101000",
    vatApplicable: true,
  },
  {
    code: "4101003",
    name: "TENDER REVENUE",
    type: "income",
    subType: "revenue",
    parentCode: "4101000",
    vatApplicable: true,
  },
  {
    code: "4101004",
    name: "PROF SERVICE RENDERED",
    type: "income",
    subType: "revenue",
    parentCode: "4101000",
    vatApplicable: true,
  },
  {
    code: "4102000",
    name: "OTHER REVENUES",
    type: "income",
    subType: "other-income",
    parentCode: "4100000",
  },
  {
    code: "5000000",
    name: "EXPENSES",
    type: "expense",
    subType: "operating-expense",
  },
  {
    code: "5100000",
    name: "GENERAL OPERATION EXPENSES",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5000000",
  },
  {
    code: "5101000",
    name: "OPERATION EXPENSES",
    type: "expense",
    subType: "cogs",
    parentCode: "5100000",
  },
  {
    code: "5101001",
    name: "DXB MUNICIPALITY FEES",
    type: "expense",
    subType: "cogs",
    parentCode: "5101000",
  },
  {
    code: "5101002",
    name: "LAND DEPT FEES",
    type: "expense",
    subType: "cogs",
    parentCode: "5101000",
  },
  {
    code: "5101003",
    name: "SOIL SURVEY & TESTING FEES",
    type: "expense",
    subType: "cogs",
    parentCode: "5101000",
  },
  {
    code: "5101004",
    name: "INSURANCE EXPENSE",
    type: "expense",
    subType: "cogs",
    parentCode: "5101000",
  },
  {
    code: "5101005",
    name: "PROFESSIONAL FEES & STUDIES",
    type: "expense",
    subType: "cogs",
    parentCode: "5101000",
  },
  {
    code: "5101006",
    name: "LEGAL FEES EXP.",
    type: "expense",
    subType: "cogs",
    parentCode: "5101000",
  },
  {
    code: "5101007",
    name: "OUTSOURCE PROF. FEES",
    type: "expense",
    subType: "cogs",
    parentCode: "5101000",
  },
  {
    code: "5101008",
    name: "EGYPT OFFICE EXP.",
    type: "expense",
    subType: "cogs",
    parentCode: "5101000",
  },
  {
    code: "5101009",
    name: "COMMISSION EXPENSE",
    type: "expense",
    subType: "cogs",
    parentCode: "5101000",
  },
  {
    code: "5102000",
    name: "ADMINISTRATIVE EXPENSES",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5100000",
  },
  {
    code: "5102001",
    name: "RENT,SERVICE CHRG,RERA",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5102000",
  },
  {
    code: "5102002",
    name: "DEWA EXPENSES",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5102000",
  },
  {
    code: "5102003",
    name: "TELEPHONE & INTERNET",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5102000",
  },
  {
    code: "5102004",
    name: "PETROL EXPENSES",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5102000",
  },
  {
    code: "5102005",
    name: "PARKING, TRANSPO & SALIK EXPENSES",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5102000",
  },
  {
    code: "5102006",
    name: "VEHICLE REPAIRS & MAINTENANCE",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5102000",
  },
  {
    code: "5102007",
    name: "GOVT RELATED EXPENSES",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5102000",
  },
  {
    code: "5102008",
    name: "PRINTING & STATIONARY",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5102000",
  },
  {
    code: "5102009",
    name: "COMPUTER EXPENSES",
    type: "expense",
    subType: "admin-expense",
    parentCode: "5102000",
  },
  {
    code: "5102010",
    name: "ADS & MARKETING EXPENSES",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102011",
    name: "OFFICE SUPPLIES",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102012",
    name: "REPAIRS & MAINTENANCE EXP",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102013",
    name: "BANK CHARGES",
    type: "expense",
    subType: "finance-expense",
    parentCode: "5102000",
  },
  {
    code: "5102014",
    name: "AUDIT FEES",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102015",
    name: "MISCELLANEOUS EXP.",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102016",
    name: "BAD DEBTS EXPENSE",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102017",
    name: "DONATION EXP.",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102018",
    name: "DEPRECIATION EXPENSE",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102019",
    name: "TRAVEL EXPENSES",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102020",
    name: "SUBSCRIPTION EXPENSE",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102021",
    name: "IT FEES",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5102022",
    name: "CORPORATE TAX EXPENSE",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5102000",
  },
  {
    code: "5103000",
    name: "EMPLOYEES EXPENSE",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5100000",
  },
  {
    code: "5103001",
    name: "SALARIES & WAGES",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5103000",
  },
  {
    code: "5103002",
    name: "LEAVE W/ WAGES",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5103000",
  },
  {
    code: "5103004",
    name: "AIR TICKET EXPENSE",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5103000",
  },
  {
    code: "5103005",
    name: "GRATUITY EXPENSE",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5103000",
  },
  {
    code: "5103006",
    name: "BONUS & INCENTIVES",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5103000",
  },
  {
    code: "5103007",
    name: "STAFF MEDICAL INSURANCE EXP",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5103000",
  },
  {
    code: "5103008",
    name: "LABOUR & IMMIGRATION",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5103000",
  },
  {
    code: "5103003",
    name: "PENSION EXPENSE",
    type: "expense",
    subType: "operating-expense",
    parentCode: "5103000",
  },
];
