import {
  pgEnum,
  pgTable,
  uuid,
  text,
  timestamp,
  date,
  integer,
  numeric,
  boolean,
  jsonb,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { users } from "./auth.js";
import { companies } from "./enterprise.js";
import { files } from "./files.js";
import { projects } from "./projects.js";
import { customers, suppliers, arInvoices, apBills } from "./finance.js";

const N16 = { precision: 16, scale: 2 } as const;

export const eInvoiceDirectionEnum = pgEnum("e_invoice_direction", ["issued", "received"]);
export const eInvoiceCategoryEnum = pgEnum("e_invoice_category", [
  "tax-invoice",
  "self-billed-tax",
  "tax-credit-note",
  "self-billed-credit",
  "commercial-invoice",
  "commercial-credit-note",
]);
export const eInvoiceStatusEnum = pgEnum("e_invoice_status", [
  "draft",
  "received",
  "pending-approval",
  "submitted",
  "validated",
  "transmitted",
  "confirmed",
  "approved",
  "posted",
  "rejected",
  "failed",
  "cancelled",
]);
export const eInvoiceScenarioEnum = pgEnum("e_invoice_scenario", [
  "free-zone",
  "deemed-supply",
  "margin-scheme",
  "summary",
  "continuous-supply",
  "agent-billing",
  "e-commerce",
  "exports",
]);

export const eInvoiceCompanyProfiles = pgTable(
  "e_invoice_company_profiles",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    tin: text("tin"),
    trn: text("trn"),
    participantId: text("participant_id"),
    legalName: text("legal_name").notNull(),
    tradeLicenseAuthority: text("trade_license_authority"),
    registrationType: text("registration_type"),
    registrationId: text("registration_id"),
    address: jsonb("address").notNull().default({}),
    vatRegistered: boolean("vat_registered").notNull().default(true),
    taxGroupMember: boolean("tax_group_member").notNull().default(false),
    taxGroupTin: text("tax_group_tin"),
    annualRevenueBand: text("annual_revenue_band").notNull().default("above50m"),
    aspName: text("asp_name"),
    aspEndpoint: text("asp_endpoint"),
    aspEnvironment: text("asp_environment").notNull().default("simulation"),
    aspStatus: text("asp_status").notNull().default("not-configured"),
    aspCredentialRef: text("asp_credential_ref"),
    aspAppointmentDeadline: date("asp_appointment_deadline"),
    goLiveDate: date("go_live_date"),
    voluntaryOnboardingDate: date("voluntary_onboarding_date"),
    retentionYears: integer("retention_years").notNull().default(5),
    notes: text("notes"),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
    updatedByUserId: uuid("updated_by_user_id").references(() => users.id, { onDelete: "set null" }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    deletedByUserId: uuid("deleted_by_user_id").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    companyUq: uniqueIndex("e_invoice_company_profiles_company_uq").on(t.companyId),
    companyIdx: index("e_invoice_company_profiles_company_idx").on(t.companyId),
    deletedIdx: index("e_invoice_company_profiles_deleted_at_idx").on(t.deletedAt),
  }),
);

export const eInvoiceClients = pgTable(
  "e_invoice_clients",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    customerId: uuid("customer_id").references(() => customers.id, { onDelete: "set null" }),
    code: text("code").notNull(),
    name: text("name").notNull(),
    tin: text("tin"),
    trn: text("trn"),
    legalRegId: text("legal_reg_id"),
    legalRegType: text("legal_reg_type"),
    electronicAddress: text("electronic_address"),
    electronicIdentifier: text("electronic_identifier"),
    address: jsonb("address").notNull().default({}),
    freeZone: boolean("free_zone").notNull().default(false),
    freeZoneEntity: text("free_zone_entity"),
    beneficiaryName: text("beneficiary_name"),
    beneficiaryAddress: text("beneficiary_address"),
    onEInvoicingSystem: boolean("on_e_invoicing_system").notNull().default(false),
    active: boolean("active").notNull().default(true),
    notes: text("notes"),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
    updatedByUserId: uuid("updated_by_user_id").references(() => users.id, { onDelete: "set null" }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    deletedByUserId: uuid("deleted_by_user_id").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    companyCodeUq: uniqueIndex("e_invoice_clients_company_code_uq").on(t.companyId, t.code),
    companyIdx: index("e_invoice_clients_company_idx").on(t.companyId),
    customerIdx: index("e_invoice_clients_customer_idx").on(t.customerId),
    trnIdx: index("e_invoice_clients_trn_idx").on(t.trn),
    deletedIdx: index("e_invoice_clients_deleted_at_idx").on(t.deletedAt),
  }),
);

export const eInvoiceDocuments = pgTable(
  "e_invoice_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    direction: eInvoiceDirectionEnum("direction").notNull(),
    category: eInvoiceCategoryEnum("category").notNull(),
    status: eInvoiceStatusEnum("status").notNull().default("draft"),
    invoiceNumber: text("invoice_number").notNull(),
    invoiceUuid: text("invoice_uuid").notNull(),
    issueDate: date("issue_date").notNull(),
    dueDate: date("due_date"),
    currencyCode: text("currency_code").notNull().default("AED"),
    transactionTypeCode: text("transaction_type_code").notNull(),
    paymentMeansCode: text("payment_means_code").notNull().default("30"),
    scenario: eInvoiceScenarioEnum("scenario").notNull().default("continuous-supply"),
    seller: jsonb("seller").notNull().default({}),
    buyer: jsonb("buyer").notNull().default({}),
    lines: jsonb("lines").notNull().default([]),
    taxBreakdown: jsonb("tax_breakdown").notNull().default([]),
    totalNetAmount: numeric("total_net_amount", N16).notNull().default("0"),
    totalTaxAmount: numeric("total_tax_amount", N16).notNull().default("0"),
    totalWithTax: numeric("total_with_tax", N16).notNull().default("0"),
    amountDue: numeric("amount_due", N16).notNull().default("0"),
    retentionExpiry: date("retention_expiry"),
    xmlGenerated: boolean("xml_generated").notNull().default(false),
    pdfGenerated: boolean("pdf_generated").notNull().default(false),
    xmlFileId: uuid("xml_file_id").references(() => files.id, { onDelete: "set null" }),
    pdfFileId: uuid("pdf_file_id").references(() => files.id, { onDelete: "set null" }),
    arInvoiceId: uuid("ar_invoice_id").references(() => arInvoices.id, { onDelete: "set null" }),
    apBillId: uuid("ap_bill_id").references(() => apBills.id, { onDelete: "set null" }),
    eInvoiceClientId: uuid("e_invoice_client_id").references(() => eInvoiceClients.id, { onDelete: "set null" }),
    customerId: uuid("customer_id").references(() => customers.id, { onDelete: "set null" }),
    supplierId: uuid("supplier_id").references(() => suppliers.id, { onDelete: "set null" }),
    projectId: uuid("project_id").references(() => projects.id, { onDelete: "set null" }),
    projectName: text("project_name"),
    milestone: text("milestone"),
    poRef: text("po_ref"),
    grnRef: text("grn_ref"),
    matchStatus: text("match_status"),
    precedingInvoiceRef: text("preceding_invoice_ref"),
    precedingInvoiceUuid: text("preceding_invoice_uuid"),
    statusHistory: jsonb("status_history").notNull().default([]),
    sourcePayload: jsonb("source_payload").notNull().default({}),
    aspSubmissionId: text("asp_submission_id"),
    aspLastResponse: jsonb("asp_last_response"),
    aspSubmittedAt: timestamp("asp_submitted_at", { withTimezone: true }),
    confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
    failedReason: text("failed_reason"),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
    updatedByUserId: uuid("updated_by_user_id").references(() => users.id, { onDelete: "set null" }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    deletedByUserId: uuid("deleted_by_user_id").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    uuidUq: uniqueIndex("e_invoice_documents_uuid_uq").on(t.invoiceUuid),
    companyDirectionNumberUq: uniqueIndex("e_invoice_documents_company_direction_number_uq").on(t.companyId, t.direction, t.invoiceNumber),
    companyStatusIdx: index("e_invoice_documents_company_status_idx").on(t.companyId, t.status),
    companyIssueIdx: index("e_invoice_documents_company_issue_idx").on(t.companyId, t.issueDate),
    directionIdx: index("e_invoice_documents_direction_idx").on(t.direction),
    arIdx: index("e_invoice_documents_ar_idx").on(t.arInvoiceId),
    apIdx: index("e_invoice_documents_ap_idx").on(t.apBillId),
    customerIdx: index("e_invoice_documents_customer_idx").on(t.customerId),
    supplierIdx: index("e_invoice_documents_supplier_idx").on(t.supplierId),
    projectIdx: index("e_invoice_documents_project_idx").on(t.projectId),
    deletedIdx: index("e_invoice_documents_deleted_at_idx").on(t.deletedAt),
  }),
);

export const eInvoiceEvents = pgTable(
  "e_invoice_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    documentId: uuid("document_id").references(() => eInvoiceDocuments.id, { onDelete: "cascade" }),
    status: eInvoiceStatusEnum("status").notNull(),
    message: text("message").notNull(),
    payload: jsonb("payload").notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    documentIdx: index("e_invoice_events_document_idx").on(t.documentId, t.createdAt),
    companyIdx: index("e_invoice_events_company_idx").on(t.companyId, t.createdAt),
  }),
);

export const eInvoiceWebhookLogs = pgTable(
  "e_invoice_webhook_logs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    companyId: uuid("company_id").references(() => companies.id, { onDelete: "set null" }),
    provider: text("provider").notNull(),
    eventType: text("event_type").notNull(),
    externalId: text("external_id"),
    payload: jsonb("payload").notNull().default({}),
    processed: boolean("processed").notNull().default(false),
    processedAt: timestamp("processed_at", { withTimezone: true }),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    providerEventIdx: index("e_invoice_webhook_logs_provider_event_idx").on(t.provider, t.eventType),
    externalIdx: index("e_invoice_webhook_logs_external_idx").on(t.externalId),
    createdIdx: index("e_invoice_webhook_logs_created_idx").on(t.createdAt),
  }),
);
